### PR TITLE
docs: add some IS and CL clarifications

### PR DESCRIPTION
**Pull request by thephez**
Update description of RPC `instantlock` fields, add links to glossary, and add links to more info from glossary entries

Preview build: https://dash-docs--105.org.readthedocs.build/projects/core/en/105/

### CODE REVIEW

**Comment by riongull** [comment]
Thanks for updating the docs with these clarifications, @thephez.  This will help devs new to Dash.

**Comment by coolaj86** [comment]
Note: it would also be good to have "Remote Procedure Calls" named "Remote Procedure Calls (RPC)" or just "RPC" so that when trying to search the docs it's easier to find it in the menu.

(I don't think anyone ever says or refers to RPC as "Remote Procedure Call" outside of an academic setting - much like REST, it's kinda lost it's meaning through it's colloquial use)

**Comment by thephez** [comment]
> Note: it would also be good to have "Remote Procedure Calls" named "Remote Procedure Calls (RPC)" or just "RPC" so that when trying to search the docs it's easier to find it in the menu via Ctrl+F / Cmd+F.
> 
> (I don't think anyone ever says or refers to RPC as "Remote Procedure Call" outside of an academic setting - much like REST, it's kinda lost it's meaning through it's colloquial use)

Just to clarify, are you referring to the name of this section?

image

**Comment by coolaj86** [comment]
Yes. That's correct. Though it's strange that when I searched I don't recall it scrolling to the "Address Index RPCs" either.

**Pull request merged**
