### PR TITLE
docs(rpc): remaining v21.0.0 rpc updates

### PR DESCRIPTION
**Pull request by thephez**
Preview build: https://dash-docs--109.org.readthedocs.build/projects/core/en/109/

### CODE REVIEW

**Comment by riongull** [comment]
Do these "v21.0.0" docs updates include the changes for "v21.1.0" (if any)? 

If we don't have docs updates on minor or patch versions would it be better to call them "v21" instead?

**Comment by thephez** [comment]
This PR doesn't include 21.1 changes, although I don't believe see are any related to RPCs (https://github.com/dashpay/dash/compare/v21.0.0...dashpay:v21.1.0). 

As for the branch name, readthedocs (which builds/hosts the content) expects a semver "x.y.z" format for automatically recognizing what to direct people to as the default docs. For example, when you go to docs.dash.org it directs you to https://docs.dash.org/en/stable/ which is the same as if you chose 21.0.0 from the version selector. So v21 might be better, but there are some constraints in play :slightly_smiling_face: 

image.

**Comment by riongull** [comment]
Yeah, I've seen the selector on the website, which is why I'm asking follow up questions. It seems to only show major versions like v19.0.0, v20.0.0, etc, so it makes me wonder if v20.0.0 docs are really for the latest v20 docs or literally for v20.0.0. Is there (or will there be) any difference between "latest", v21.0.0, and v21.1.0 (if there will eventually be a separate docs page for that).

If you can change the text to v19, v20, etc

**Comment by thephez** [comment]
Since Core is now following semver pretty closely, expect to typically just see 21.0.0, 22.0.0, etc. Minor/patch releases should not be making changes significant enough to require a new version of docs. So when you see "X.0.0", assume they're good for all of "vX". In the future if there were a minor/patch version of docs it would likely be due to a deviation in Core's semver that significantly changed something. I don't anticipate Pasta doing that though :slightly_smiling_face: 

Regarding the dropdown text... Based on a cursory look, readthedocs directly uses the branch/tag name as the text in the dropdown. I didn't see an option for customizing it.

**Pull request merged**
